(function(){'use strict';
const API='https://travel-ai.luckyjungheywon.workers.dev';
function C(){try{return typeof window.C==='function'?window.C():(0,eval)('C()')}catch(e){return null}}
function save(){try{(0,eval)('save()')}catch(e){console.warn('Afield save failed',e)}}
function dates(c){try{return (0,eval)('tripDates(C())')}catch(e){return []}}
function days(c){return Array.isArray(c?.plan?.days)?c.plan.days:[]}
function norm(s){return String(s||'').toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu,'')}
function todayISO(){return new Date().toLocaleDateString('en-CA')}
function todayIndex(c){const ds=dates(c),iso=todayISO(),i=ds.findIndex(d=>d.iso===iso);if(i>=0)return i;const a=Date.parse((c.start||'')+'T00:00:00'),b=Date.parse((c.end||'')+'T23:59:59'),n=Date.now();if(n>b)return Math.max(0,ds.length-1);if(n<a)return 0;return Math.min(Math.max(0,Math.floor((n-a)/86400000)),Math.max(0,ds.length-1))}
function mins(v){const m=String(v||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function itemPast(x,di,c){const ti=todayIndex(c);if(di<ti)return true;if(di>ti)return false;if(x?.completed||x?.done)return true;const m=mins(x?.arrivalTime||x?.start||x?.time);const d=new Date();return m!=null&&m<d.getHours()*60+d.getMinutes()}
function tasks(c){if(!Array.isArray(c.agentTasks))c.agentTasks=[];return c.agentTasks}
function allPlaces(c){const out=[];for(const d of days(c))for(const l of ['items','nearby','backup'])for(const x of(d[l]||[]))out.push(x);for(const x of(c.saved||[]))if(x&&typeof x==='object'&&x.sourceType!=='instagram')out.push(x);const seen=new Set();return out.filter(x=>{const k=x.placeId||norm(x.name);if(!k||seen.has(k))return false;seen.add(k);return true})}
function stayState(c){const t=todayISO(),ss=c.stays||[];const current=ss.find(s=>(!s.checkIn||s.checkIn<=t)&&(!s.checkOut||t<s.checkOut))||null;const next=ss.filter(s=>s.checkIn&&s.checkIn>t).sort((a,b)=>a.checkIn.localeCompare(b.checkIn))[0]||null;return{current,next}}
function mini(x,di,c){return{name:x?.name||'',placeId:x?.placeId||'',address:x?.address||'',priority:x?.priority||'',locked:!!x?.locked,completed:!!(x?.completed||x?.done),completedAt:x?.completedAt||'',arrivalTime:x?.arrivalTime||'',lat:x?.lat??null,lng:x?.lng??null,openingHours:x?.regularOpeningHours||null,immutable:itemPast(x,di,c)||!!x?.locked}}
function state(c){const ti=todayIndex(c),ds=dates(c),st=stayState(c);return{now:new Date().toISOString(),todayIndex:ti,city:c.city||'',country:c.country||'',currentStay:st.current,nextStay:st.next,days:days(c).map((d,i)=>({dayIndex:i,date:ds[i]?.iso||d.date||'',theme:d.theme||'',immutable:i<ti,route:(d.items||[]).map(x=>mini(x,i,c)),nearby:(d.nearby||[]).map(x=>mini(x,i,c)),backup:(d.backup||[]).map(x=>mini(x,i,c)})),tasks:tasks(c).map(x=>({id:x.id,name:x.name,status:x.done?'DONE':(x.status||'OPEN'),completedAt:x.completedAt||''})),buyList:(c.buyList||[]).map(x=>({id:x.id,name:x.name,done:!!x.done,completedAt:x.completedAt||'',placeName:x.placeName||''})),rules:{historyImmutable:true,completedImmutable:true,preserveEverythingUnlessAffected:true,protectLocked:true,protectMust:true}}}
async function api(path,body){const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||('HTTP '+r.status));return d}
async function plan(request){const c=C(),s=state(c);const d=await api('/plan',{mode:'live_trip_repair',request,state:s,rules:{neverRewritePast:true,neverChangeCompleted:true,preserveEverythingUnlessAffected:true,neverRebuildWholeTrip:true,newUnknownPlaceMustRemainTaskUntilVerified:true}});return{request,changed:d.changed||d.changes||d.suggestions||[],preserved:d.preserved||[],reasons:d.reasons||d.reason||[],tasks:d.tasks||[],raw:d}}
function findPlace(o,c){const q=norm(o.placeName||o.name||o.targetPlace||o.venue||o.place?.name||''),txt=norm([o.action,o.summary,o.title].filter(Boolean).join(' '));const a=allPlaces(c);return a.find(x=>q&&norm(x.name)===q)||a.find(x=>q&&norm(x.name).includes(q))||a.find(x=>txt&&txt.includes(norm(x.name)))||null}
function loc(p,c){if(!p)return null;for(let di=0;di<days(c).length;di++)for(const l of['items','nearby','backup']){const a=days(c)[di][l]||[],ix=a.findIndex(x=>(p.placeId&&x.placeId===p.placeId)||norm(x.name)===norm(p.name));if(ix>=0)return{di,l,ix,item:a[ix]}}return null}
function day(o,c){for(const v of[o.dayIndex,o.targetDay,o.toDay,o.day,o.targetDate,o.date]){if(v==null||v==='')continue;if(Number.isInteger(v)&&v>=0&&v<days(c).length)return v;const n=Number(v);if(Number.isFinite(n)&&n>=1&&n<=days(c).length)return n-1;const iso=String(v).match(/\d{4}-\d{2}-\d{2}/)?.[0];if(iso){const i=dates(c).findIndex(d=>d.iso===iso);if(i>=0)return i}}return-1}
function type(o){const t=[o.type,o.kind,o.operation,o.actionType,o.action,o.summary,o.title].filter(Boolean).join(' ').toUpperCase();if(t.includes('THEME'))return'THEME';if(t.includes('MOVE')||t.includes('RESCHEDULE'))return'MOVE';if(t.includes('ADD'))return'ADD';if(t.includes('DROP')||t.includes('REMOVE'))return'DROP';if(t.includes('NEARBY')||t.includes('BACKUP')||t.includes('LAYER'))return'LAYER';if(t.includes('PRIORITY')||t.includes('MUST'))return'PRIORITY';if(t.includes('TASK'))return'TASK';return'CHANGE'}
function layer(o){const s=String(o.targetLayer||o.layer||o.routeLayer||'ROUTE').toUpperCase();return s.includes('NEAR')?'nearby':s.includes('BACK')?'backup':'items'}
async function compile(changes){try{const d=await api('/plan',{mode:'compile_live_trip_repair',approvedChanges:changes,state:state(C()),allowedOperations:['THEME','MOVE','ADD','DROP','LAYER','PRIORITY','TASK'],rules:{historyImmutable:true,completedImmutable:true,exactDayIndex:true}});return d.operations||d.patches||d.changes||changes}catch(e){return changes}}
async function applyOp(o,c){const t=type(o),di=day(o,c),p=findPlace(o,c),at=loc(p,c),l=layer(o),ti=todayIndex(c);if(t==='TASK'){const name=o.task||o.taskName||o.summary||o.title||o.action;if(!name)return{ok:false,reason:'Task name missing'};if(!tasks(c).some(x=>!x.done&&norm(x.name)===norm(name)))tasks(c).push({id:'task_'+Date.now()+Math.random().toString(36).slice(2,5),name,status:'OPEN',createdAt:new Date().toISOString(),done:false});return{ok:true,label:name}}if(di>=0&&di<ti)return{ok:false,reason:'Past day is history'};if(t==='THEME'&&di>=0){days(c)[di].theme=String(o.theme||o.value||o.title||o.summary||'').trim();return{ok:true,label:'Day '+(di+1)+' theme'}}if(t==='DROP'){if(!at)return{ok:false,reason:'Place not found'};if(itemPast(at.item,at.di,c)||at.item.locked||String(at.item.priority||'').toUpperCase()==='MUST')return{ok:false,reason:'Protected history/MUST'};days(c)[at.di][at.l].splice(at.ix,1);return{ok:true,label:at.item.name}}if(t==='MOVE'||t==='LAYER'){if(di<0||!at)return{ok:false,reason:'Target not resolved'};if(itemPast(at.item,at.di,c)||at.item.locked)return{ok:false,reason:'Past/completed/locked'};const[x]=days(c)[at.di][at.l].splice(at.ix,1);x.userEdited=true;x.routeLayer=l==='items'?'ROUTE':l.toUpperCase();days(c)[di][l]=days(c)[di][l]||[];days(c)[di][l].push(x);return{ok:true,label:x.name}}if(t==='PRIORITY'&&p){if(at&&itemPast(at.item,at.di,c))return{ok:false,reason:'Past/completed'};p.priority=String(o.priority||o.value||'MUST').toUpperCase();return{ok:true,label:p.name}}if(t==='ADD'){if(di<0)return{ok:false,reason:'Target day missing'};if(!p)return{ok:false,reason:'New place must be verified first'};if(at)return{ok:false,reason:'Already in itinerary'};days(c)[di][l]=days(c)[di][l]||[];days(c)[di][l].push({...p,userEdited:true,routeLayer:l==='items'?'ROUTE':l.toUpperCase()});return{ok:true,label:p.name}}return{ok:false,reason:'Unsupported operation'}}
async function apply(changes){const c=C(),ops=await compile(changes),applied=[],failed=[];for(const o of ops){const r=await applyOp(o,c);(r.ok?applied:failed).push({label:r.label||o.summary||o.title||o.action||'Change',reason:r.reason||''})}save();return{applied,failed,ops}}
window.AfieldAgentCore={C,state,plan,apply,tasks,save,todayIndex,itemPast};})();