(function(){
'use strict';
const STYLE='__afieldDoneStyle';
function C(){try{return typeof window.C==='function'?window.C():(0,eval)('C()')}catch(e){return null}}
function persist(){try{(0,eval)('save()')}catch(e){console.warn('Afield done persist failed',e)}}
function rerender(){try{(0,eval)('chapter()')}catch(e){try{window.chapter?.()}catch(_){}}}
function norm(s){return String(s||'').toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu,'')}
function activeDay(){const ey=document.querySelector('.brief .ey');const m=(ey?.textContent||'').match(/DAY\s*(\d+)/i);return m?Math.max(0,Number(m[1])-1):0}
function styles(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`.afDoneRow{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:14px;padding-top:12px;border-top:1px solid #ecece7}.afDoneBtn{border:1px solid #d9d9d4;background:#fff;border-radius:999px;padding:9px 13px;font-size:12px;font-weight:850}.afDoneBtn.done{background:#111;color:#fff;border-color:#111}.routeCard.afCompleted{opacity:.58}.routeCard.afCompleted h2{text-decoration:line-through;text-decoration-thickness:1px}.afDoneMeta{font-size:11px;color:#888}.aaTaskDone{border:1px solid #d9d9d4;background:#fff;border-radius:999px;padding:7px 10px;font-size:11px;font-weight:850}.aaTaskDone.done{background:#111;color:#fff}`;document.head.appendChild(s)}
function findItem(c,di,name){const d=c?.plan?.days?.[di];if(!d)return null;for(const layer of ['items','nearby','backup']){const a=d[layer]||[];const x=a.find(x=>norm(x.name)===norm(name));if(x)return x}return null}
function toggle(di,name){const c=C(),x=findItem(c,di,name);if(!x)return;x.completed=!x.completed;x.completedAt=x.completed?new Date().toISOString():null;x.userEdited=true;c.completionLog=Array.isArray(c.completionLog)?c.completionLog:[];c.completionLog.push({kind:'ITINERARY',name:x.name,dayIndex:di,done:!!x.completed,at:new Date().toISOString()});persist();rerender()}
function injectRouteDone(){const c=C();if(!c?.plan?.days)return;const di=activeDay();document.querySelectorAll('.routeCard').forEach(card=>{if(card.querySelector('.afDoneRow'))return;const name=card.querySelector('h2')?.textContent?.trim();if(!name)return;const x=findItem(c,di,name);if(!x)return;card.classList.toggle('afCompleted',!!x.completed);const row=document.createElement('div');row.className='afDoneRow';const meta=x.completedAt?`Done · ${new Date(x.completedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'Not done yet';row.innerHTML=`<span class="afDoneMeta">${meta}</span><button type="button" class="afDoneBtn ${x.completed?'done':''}">${x.completed?'✓ Done':'Mark done'}</button>`;row.querySelector('button').onclick=()=>toggle(di,name);card.appendChild(row)})}
function injectTaskDone(){const c=C();if(!Array.isArray(c?.agentTasks))return;document.querySelectorAll('[data-agent-task-id]').forEach(el=>{if(el.querySelector('.aaTaskDone'))return;const id=el.dataset.agentTaskId,x=c.agentTasks.find(t=>t.id===id);if(!x)return;const b=document.createElement('button');b.className='aaTaskDone '+(x.done?'done':'');b.textContent=x.done?'✓ Done':'Done';b.onclick=()=>{x.done=!x.done;x.completedAt=x.done?new Date().toISOString():null;persist();rerender()};el.appendChild(b)})}
function trackBuyClick(e){const btn=e.target.closest?.('.buyCheck');if(!btn)return;const item=btn.closest('.buyItem');if(!item)return;const name=item.querySelector('b')?.textContent?.trim();if(!name)return;setTimeout(()=>{const c=C(),x=(c?.buyList||[]).find(v=>norm(v.name)===norm(name));if(!x)return;x.completedAt=x.done?(x.completedAt||new Date().toISOString()):null;c.completionLog=Array.isArray(c.completionLog)?c.completionLog:[];c.completionLog.push({kind:'BUY',name:x.name,done:!!x.done,at:new Date().toISOString()});persist()},0)}
function inject(){styles();injectRouteDone();injectTaskDone()}
document.addEventListener('click',trackBuyClick,false);
const mo=new MutationObserver(()=>{clearTimeout(window.__afDoneT);window.__afDoneT=setTimeout(inject,50)});mo.observe(document.documentElement,{childList:true,subtree:true});setTimeout(inject,100);window.AfieldDone={toggle};
})();