(function(){
'use strict';
const API='https://travel-ai.luckyjungheywon.workers.dev';
const ID='__afieldRefineCardV2';
const MODAL='__afieldRefineModalV2';
const STYLE='__afieldRefineStyleV2';
const PROMPT_HINT='예: 기존 일정은 유지하면서 Healing Day, Marais Fashion & Vintage Day, Culture & Inspiration Day처럼 날짜별 character를 만들어줘. MUST·고정 일정·영업시간을 보존하고, Simple Rainbow·Merci·Brigitte Tanaka·모네 수련 전시 등 내가 원하는 경험을 자연스럽게 재배치해줘. 먼저 변경안을 보여주고 승인 후 적용해줘.';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function C(){try{return typeof window.C==='function'?window.C():null}catch(e){return null}}
function save(){try{if(typeof window.save==='function')window.save()}catch(e){}}
function days(c){return Array.isArray(c?.plan?.days)?c.plan.days:[]}
function k(x){return String(x?.placeId||x?.name||'').toLowerCase()}
function allPlaces(c){const out=[];for(const d of days(c)){for(const layer of ['items','nearby','backup'])for(const x of (d[layer]||[]))out.push(x)}for(const x of (c?.saved||[]))if(x&&typeof x!=='string'&&x.sourceType!=='instagram')out.push(x);const seen=new Set();return out.filter(x=>{const key=k(x);if(!key||seen.has(key))return false;seen.add(key);return true})}
function inspirations(c){return (c?.saved||[]).filter(x=>x&&typeof x!=='string'&&x.sourceType==='instagram').slice(0,80).map(x=>({title:x.name||'',url:x.source||x.instagramUrl||'',context:x.why||x.caption||'',candidates:x.candidates||[]}))}
function payload(c,request,verifyHours){return {
 mode:'refine_existing_itinerary',request,verifyHours:!!verifyHours,protectMust:true,preserveExistingPlan:true,requireApprovalBeforeApply:true,
 rules:{doNotRebuildFromScratch:true,preserveFixedEvents:true,preserveHotelsAndTransfers:true,preserveLocked:true,preserveUserEdited:true,dedupePlacesAndBuyList:true,unknownInstagramPlacesStayInspiration:true,groupByArea:true,routeLayers:['ROUTE','NEARBY','BACKUP']},
 trip:{title:c.title||'',city:c.city||'',country:c.country||'',start:c.start||'',end:c.end||'',stays:c.stays||[],transports:c.transports||c.flights||[],priorBrief:c.refineBrief||''},
 itinerary:days(c).map((d,i)=>({day:i+1,date:d.date||'',theme:d.theme||'',route:(d.items||[]).map(minPlace),nearby:(d.nearby||[]).map(minPlace),backup:(d.backup||[]).map(minPlace)})),
 places:allPlaces(c).slice(0,320).map(minPlace),
 buyList:(c.buyList||[]).slice(0,160).map(x=>({name:x.name||'',placeName:x.placeName||'',priority:x.priority||'',category:x.category||'',done:!!x.done,instagramUrl:x.instagramUrl||''})),
 inspirations:inspirations(c)
}}
function minPlace(x){return {name:x?.name||'',placeId:x?.placeId||'',address:x?.address||'',priority:x?.priority||'',routeLayer:x?.routeLayer||'',category:x?.category||x?.primaryType||'',why:x?.why||'',source:x?.source||'',locked:!!x?.locked,userEdited:!!x?.userEdited,lat:x?.lat??null,lng:x?.lng??null}}
function styles(){if(document.getElementById(STYLE))return;const s=document.createElement('style');s.id=STYLE;s.textContent=`#${ID}{border:1px solid #deded8;background:linear-gradient(145deg,#fff,#f3f3ef);border-radius:26px;padding:22px;margin:16px 0 20px}#${ID} .top{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}#${ID} h2{font-size:28px;letter-spacing:-.045em;margin:6px 0 7px}#${ID} p{margin:0;color:#73736e;line-height:1.5;font-size:14px}#${ID} button,.rvBtn{border:0;border-radius:999px;padding:12px 17px;font-weight:800;background:#111;color:#fff}.rvModal{position:fixed;inset:0;z-index:2147483000;background:#0007;display:flex;align-items:flex-end;justify-content:center;padding:8px}.rvSheet{width:min(760px,100%);max-height:90vh;overflow:auto;background:#fbfbf9;border-radius:30px 30px 18px 18px;padding:26px}.rvEy{font-size:11px;letter-spacing:.2em;font-weight:850;color:#888}.rvSheet h2{font-size:30px;letter-spacing:-.045em;margin:8px 0 9px}.rvSheet p{color:#777;line-height:1.5}.rvTextarea{width:100%;min-height:260px;resize:vertical;border:1px solid #dcdcd6;background:#fff;border-radius:20px;padding:16px;font:16px/1.5 -apple-system,BlinkMacSystemFont,sans-serif;outline:none}.rvRow{display:flex;align-items:center;gap:9px;margin:12px 0;font-size:13px;color:#555}.rvActions{display:flex;gap:9px;margin-top:18px}.rvBtn.alt{background:#e8e8e4;color:#111}.rvBtn.primary{flex:1}.rvChange{border:1px solid #deded8;background:#fff;border-radius:20px;padding:15px;margin:10px 0;display:grid;grid-template-columns:22px 1fr;gap:11px}.rvMeta{font-size:11px;font-weight:800;letter-spacing:.08em;color:#888;margin-bottom:4px}.rvReason{font-size:13px;color:#666;line-height:1.45}.rvStatus{border-radius:18px;background:#efefeb;padding:14px;margin:13px 0;font-size:13px;color:#555;line-height:1.5}.rvTheme{display:inline-flex;margin:8px 0 4px;border-radius:999px;background:#111;color:#fff;padding:7px 10px;font-size:11px;font-weight:800}.rvSaved{margin-top:14px;padding-top:14px;border-top:1px solid #e1e1db;font-size:13px;color:#666}@media(min-width:761px){.rvModal{align-items:center;padding:20px}.rvSheet{border-radius:30px}}@media(max-width:620px){#${ID} .top{display:block}#${ID} button{margin-top:14px}.rvSheet h2{font-size:27px}}`;document.head.appendChild(s)}
function close(){document.getElementById(MODAL)?.remove()}
function modal(html){close();const m=document.createElement('div');m.id=MODAL;m.className='rvModal';m.innerHTML=`<div class="rvSheet">${html}</div>`;m.onclick=e=>{if(e.target===m)close()};document.body.appendChild(m)}
function openComposer(){const c=C();if(!c)return;modal(`<div class="rvEy">REFINE WITH AFIELD</div><h2>Tell Afield how you want this trip to feel.</h2><p>현재 itinerary를 기본으로 유지하면서, 여행 취향·테마·구매 목표·새로운 inspiration을 반영해요. 변경 전에는 반드시 제안안을 먼저 보여줘요.</p><textarea id="rvRequest" class="rvTextarea" placeholder="${esc(PROMPT_HINT)}">${esc(c.refineBrief||'')}</textarea><label class="rvRow"><input id="rvHours" type="checkbox" checked> 영업시간과 날짜 제약 확인</label><div class="rvActions"><button class="rvBtn alt" id="rvCancel">취소</button><button class="rvBtn primary" id="rvAsk">변경안 보기</button></div>`);document.getElementById('rvCancel').onclick=close;document.getElementById('rvAsk').onclick=ask}
async function ask(){const c=C(),q=document.getElementById('rvRequest')?.value.trim();if(!c||!q)return;const verify=!!document.getElementById('rvHours')?.checked;modal(`<div class="rvEy">REFINE WITH AFIELD</div><h2>현재 일정을 읽고 있어요.</h2><div class="rvStatus">ROUTE / NEARBY / BACKUP, 숙소 이동, MUST, Buy list, Instagram inspiration까지 함께 비교하고 있어요.</div>`);try{const r=await fetch(API+'/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(c,q,verify))});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||data.error||('HTTP '+r.status));const list=Array.isArray(data.suggestions)?data.suggestions:Array.isArray(data.changes)?data.changes:[];c._pendingRefine={request:q,suggestions:list,createdAt:new Date().toISOString()};save();review(c._pendingRefine)}catch(e){modal(`<div class="rvEy">REFINE WITH AFIELD</div><h2>변경안을 만들지 못했어요.</h2><div class="rvStatus">${esc(e.message||e)}</div><div class="rvActions"><button class="rvBtn alt" id="rvClose">닫기</button><button class="rvBtn primary" id="rvRetry">다시 쓰기</button></div>`);document.getElementById('rvClose').onclick=close;document.getElementById('rvRetry').onclick=openComposer}}
function label(s){return s.action||s.summary||s.title||[s.placeName,s.layer,s.day&&('Day '+s.day)].filter(Boolean).join(' · ')||'Change'}
function review(p){const list=p?.suggestions||[];const html=list.length?list.map((s,i)=>`<label class="rvChange"><input type="checkbox" class="rvPick" data-i="${i}" ${s.selected===false?'':'checked'}><div><div class="rvMeta">${esc(String(s.type||s.kind||'CHANGE').toUpperCase())}${s.hours_status&&s.hours_status!=='not_checked'?' · '+esc(s.hours_status):''}</div><b>${esc(label(s))}</b><div class="rvReason">${esc(s.reason||s.rationale||'')}${s.hours_note?'<br>'+esc(s.hours_note):''}</div></div></label>`).join(''):`<div class="rvStatus">제안된 변경이 없어요. 요청을 조금 더 구체적으로 써봐요.</div>`;modal(`<div class="rvEy">SUGGESTED CHANGES</div><h2>${list.length}개의 변경안을 만들었어요.</h2><p>체크한 변경만 적용해요. Afield가 확실히 연결하지 못한 장소나 Instagram 게시물은 임의 생성하지 않고 guidance로만 남겨둬요.</p>${html}<div class="rvActions"><button class="rvBtn alt" id="rvBack">다시 쓰기</button><button class="rvBtn primary" id="rvApply">선택한 변경 적용</button></div>`);document.getElementById('rvBack').onclick=openComposer;document.getElementById('rvApply').onclick=applySelected}
function dayIndex(s,c){if(Number.isInteger(s.dayIndex)&&s.dayIndex>=0&&s.dayIndex<days(c).length)return s.dayIndex;if(Number(s.day)>=1&&Number(s.day)<=days(c).length)return Number(s.day)-1;const text=[s.action,s.summary,s.title,s.date].filter(Boolean).join(' ');let m=text.match(/(?:day\s*)?(\d+)/i);if(m){const n=Number(m[1])-1;if(n>=0&&n<days(c).length)return n}m=text.match(/\b(\d{1,2})\/(\d{1,2})\b/);if(m){const md=`${Number(m[1])}/${Number(m[2])}`;const i=days(c).findIndex(d=>{const x=new Date((d.date||'')+'T12:00:00');return !Number.isNaN(x.getTime())&&`${x.getMonth()+1}/${x.getDate()}`===md});if(i>=0)return i}return -1}
function findPlace(s,c){const explicit=String(s.placeName||s.name||'').toLowerCase();const text=[s.action,s.summary,s.title].filter(Boolean).join(' ').toLowerCase();return allPlaces(c).sort((a,b)=>String(b.name||'').length-String(a.name||'').length).find(x=>explicit===String(x.name||'').toLowerCase()||text.includes(String(x.name||'').toLowerCase()))||null}
function findLoc(place,c){if(!place)return null;const key=k(place);for(let di=0;di<days(c).length;di++)for(const layer of ['items','nearby','backup']){const a=days(c)[di][layer]||[],ix=a.findIndex(x=>k(x)===key);if(ix>=0)return {di,layer,ix,item:a[ix]}}return null}
function targetLayer(s){const v=String(s.layer||s.routeLayer||'').toUpperCase();if(v==='NEARBY')return 'nearby';if(v==='BACKUP')return 'backup';return 'items'}
function themeValue(s){return String(s.theme||s.title||s.action||'').replace(/^(?:DAY|Day|day)\s*\d+\s*[-:·]?\s*/,'').trim()}
function applyOne(s,c){const type=String(s.type||s.kind||'').toUpperCase(),di=dayIndex(s,c),place=findPlace(s,c),loc=findLoc(place,c),layer=targetLayer(s);if(['RHYTHM','THEME'].includes(type)&&di>=0){days(c)[di].theme=themeValue(s);return true}if(type==='ADD'&&di>=0&&place&&!loc){days(c)[di][layer]=days(c)[di][layer]||[];days(c)[di][layer].push({...place,userEdited:true,locked:false,routeLayer:layer==='items'?'ROUTE':layer.toUpperCase()});return true}if(['MOVE','LAYER'].includes(type)&&di>=0&&loc&&!loc.item.locked){const [x]=days(c)[loc.di][loc.layer].splice(loc.ix,1);x.userEdited=true;x.routeLayer=layer==='items'?'ROUTE':layer.toUpperCase();days(c)[di][layer]=days(c)[di][layer]||[];days(c)[di][layer].push(x);return true}if(type==='DROP'&&loc&&!loc.item.locked&&String(loc.item.priority||'').toUpperCase()!=='MUST'){days(c)[loc.di][loc.layer].splice(loc.ix,1);return true}if(['PRIORITY','ANCHOR'].includes(type)&&place){place.priority=s.priority||'MUST';place.userEdited=true;return true}return false}
function applySelected(){const c=C();if(!c||!c._pendingRefine)return;const ids=[...document.querySelectorAll('.rvPick:checked')].map(x=>Number(x.dataset.i));const chosen=ids.map(i=>c._pendingRefine.suggestions[i]).filter(Boolean);c.refineUndo={plan:JSON.parse(JSON.stringify(c.plan||null)),saved:JSON.parse(JSON.stringify(c.saved||[])),buyList:JSON.parse(JSON.stringify(c.buyList||[])),at:new Date().toISOString()};let applied=0;for(const s of chosen)if(applyOne(s,c))applied++;c.refineBrief=c._pendingRefine.request;c.refineGuidance=chosen;c.refineUpdatedAt=new Date().toISOString();delete c._pendingRefine;save();close();try{if(typeof window.chapter==='function')window.chapter()}catch(e){}setTimeout(()=>{modal(`<div class="rvEy">REFINED</div><h2>${applied}개 변경을 일정에 반영했어요.</h2><div class="rvStatus">자동 적용하지 못한 ${Math.max(0,chosen.length-applied)}개는 임의로 추측하지 않고 guidance로 저장했어요. 기존 일정은 source of truth로 유지돼요.</div><div class="rvActions"><button class="rvBtn primary" id="rvDone">일정 보기</button></div>`);document.getElementById('rvDone').onclick=close},80)}
function injectTheme(){const c=C();if(!c)return;const brief=document.querySelector('.brief');if(!brief||brief.querySelector('.rvTheme'))return;const ey=brief.querySelector('.ey'),m=(ey?.textContent||'').match(/DAY\s*(\d+)/i);if(!m)return;const t=days(c)[Number(m[1])-1]?.theme;if(t){const x=document.createElement('div');x.className='rvTheme';x.textContent=t;ey.insertAdjacentElement('afterend',x)}}
function inject(){styles();const c=C();if(!c)return;const tabs=[...document.querySelectorAll('.tabs')].find(t=>[...t.querySelectorAll('button')].some(b=>b.classList.contains('on')&&b.textContent.trim()==='Trip'));if(!tabs)return;document.getElementById('__afieldRefineCard')?.remove();if(!document.getElementById(ID)){const card=document.createElement('div');card.id=ID;const saved=Array.isArray(c.refineGuidance)&&c.refineGuidance.length?`<div class="rvSaved">Last refined · ${c.refineGuidance.length} approved changes</div>`:'';card.innerHTML=`<div class="top"><div><div class="rvEy">REFINE WITH AFIELD</div><h2>Make this trip more you.</h2><p>이미 만든 itinerary는 유지하고, 테마·쇼핑·문화·휴식 취향을 더 강하게 반영해요. 먼저 변경안을 보여줘요.</p></div><button type="button">Refine this trip</button></div>${saved}`;card.querySelector('button').onclick=openComposer;tabs.insertAdjacentElement('afterend',card)}injectTheme()}
const mo=new MutationObserver(()=>{clearTimeout(window.__afieldRefineV2T);window.__afieldRefineV2T=setTimeout(inject,50)});mo.observe(document.documentElement,{childList:true,subtree:true});setTimeout(inject,0);setTimeout(inject,500);window.AfieldRefineV2={open:openComposer};
})();